import { IMovie } from './movie';

export const moviesMock: IMovie[] = [
  {
    title: 'MovieMock title 1',
    year: 'MovieMock',
    Rated: 'MovieMock',
    Released: 'MovieMock',
    Runtime: 'MovieMock',
    Genre: 'MovieMock',
    Director: 'MovieMock',
    Writer: 'MovieMock',
    Actors: 'MovieMock',
    Plot: 'MovieMock',
    Language: 'MovieMock',
    Country: 'MovieMock',
    Poster: 'MovieMock',
    Awards: 'MovieMock',
    ImdbRating: 'MovieMock',
    ImdbID: 'MovieMock1',
  },
  {
    title: 'MovieMock title 2',
    year: 'MovieMock',
    Rated: 'MovieMock',
    Released: 'MovieMock',
    Runtime: 'MovieMock',
    Genre: 'MovieMock',
    Director: 'MovieMock',
    Writer: 'MovieMock',
    Actors: 'MovieMock',
    Plot: 'MovieMock',
    Language: 'MovieMock',
    Country: 'Spain',
    Poster: 'MovieMock',
    Awards: 'MovieMock',
    ImdbRating: 'MovieMock',
    ImdbID: 'MovieMock2',
  },
  {
    title: 'MovieMock title 3',
    year: 'MovieMock',
    Rated: 'MovieMock',
    Released: 'MovieMock',
    Runtime: 'MovieMock',
    Genre: 'MovieMock',
    Director: 'MovieMock',
    Writer: 'MovieMock',
    Actors: 'MovieMock',
    Plot: 'MovieMock',
    Language: 'MovieMock',
    Country: 'Japan',
    Poster: 'MovieMock',
    Awards: 'MovieMock',
    ImdbRating: 'MovieMock',
    ImdbID: 'MovieMock3',
  }
]