import { IMovie } from './movie';

export const moviesMock: IMovie[] = [
  {
    title: 'MovieMock title 1',
    year: 'MovieMock',
    rated: 'MovieMock',
    released: 'MovieMock',
    runtime: 'MovieMock',
    genre: 'MovieMock',
    director: 'MovieMock',
    writer: 'MovieMock',
    actors: 'MovieMock',
    plot: 'MovieMock',
    language: 'MovieMock',
    country: 'MovieMock',
    poster: 'MovieMock',
    awards: 'MovieMock',
    imdbRating: 'MovieMock',
    imdbID: 'MovieMock1',
  },
  {
    title: 'MovieMock title 2',
    year: 'MovieMock',
    rated: 'MovieMock',
    released: 'MovieMock',
    runtime: 'MovieMock',
    genre: 'MovieMock',
    director: 'MovieMock',
    writer: 'MovieMock',
    actors: 'MovieMock',
    plot: 'MovieMock',
    language: 'MovieMock',
    country: 'Spain',
    poster: 'MovieMock',
    awards: 'MovieMock',
    imdbRating: 'MovieMock',
    imdbID: 'MovieMock2',
  },
  {
    title: 'MovieMock title 3',
    year: 'MovieMock',
    rated: 'MovieMock',
    released: 'MovieMock',
    runtime: 'MovieMock',
    genre: 'MovieMock',
    director: 'MovieMock',
    writer: 'MovieMock',
    actors: 'MovieMock',
    plot: 'MovieMock',
    language: 'MovieMock',
    country: 'Japan',
    poster: 'MovieMock',
    awards: 'MovieMock',
    imdbRating: 'MovieMock',
    imdbID: 'MovieMock3',
  }
]